#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true
ssh_authorized_keys:
  - ${SSH_PUBLIC_KEY}
packages:
  - python3-venv
  - python3-dev
  - build-essential
  - postgresql-server-dev-all
  - postgresql-postgis
  - postgis
  - direnv
  - unzip
snap:
  commands:
    - snap refresh
write_files:
  - path: /home/ubuntu/.bashrc
    content: |
      eval "$(direnv hook bash)"
    owner: ubuntu:ubuntu
    append: true
    defer: true
  - path: /home/ubuntu/update_aws_cli.sh
    content: |
      #!/bin/bash
      CURRENT_ARCH=$(uname -m)
      curl "https://awscli.amazonaws.com/awscli-exe-linux-${CURRENT_ARCH}.zip" -o "awscliv2.zip"
      unzip ./awscliv2.zip
      if command -v aws
      then
        echo "updating"
        sudo ./aws/install --update
      else
        echo "installing"
        sudo ./aws/install
      fi
      rm -rf ./aws
      rm -rf ./awscliv2.zip
    owner: ubuntu:ubuntu
    defer: true
    permissions: 0755
runcmd:
  - sudo -u ubuntu git config --global user.name "Johnathan Caldwell"
  - sudo -u ubuntu git config --global user.email jjcldwll@gmail.com
  - bash /home/ubuntu/update_aws_cli.sh
  # - sudo -u ubuntu curl -o /home/ubuntu/nvm-install.sh https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh
  # - sudo -u ubuntu bash /home/ubuntu/nvm-install.sh
  - curl -sL https://deb.nodesource.com/setup_lts.x | bash -
  - apt install -y nodejs
  - npm install -g npm@latest
  - npm update -g
  - npm install -g npm-check-updates
  - npm install -g aws-cdk
  - sudo -u postgres psql -c "CREATE USER geodjango PASSWORD 'geodjango';"
  - sudo -u postgres psql -c "CREATE DATABASE geodjango OWNER geodjango;"
  - sudo -u postgres psql -d geodjango -c "CREATE EXTENSION postgis;"
